context:
  name: sofa-softrobotsinverse
  version: 24.12.01
  build_num: 0
  major: ${{ (version | split('.'))[0] }}
  minor: ${{ (version | split('.'))[1] }}
  major_minor: ${{ major }}.${{ minor }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  git: https://github.com/olivier-roussel/SoftRobots.Inverse.git
  branch: v24.12.01

build:
  number: ${{ build_num }}
  string: nightly_py${{ python | version_to_buildstring }}h${{ hash }}

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - if: not win
      then: 
        - make
    - if: win
      then: 
        - ninja
    - if: linux
      then: 
        - ${{ cdt('mesa-libgl-devel') }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - pybind11        
  host:
    - sofa-devel ==${{ major_minor }}
    - sofa-python3 ==${{ major_minor }}
    - sofa-stlib ==${{ major_minor }}
    - sofa-softrobots ==${{ major_minor }}
    - eigen
    - libboost-headers
    - cxxopts
    - pybind11
    - python
    - proxsuite
  run:
    # we manually pin compatibility between sofa libs and plugins to MAJOR.MINOR versions
    - ${{ pin_compatible("sofa-devel", lower_bound='x.x', upper_bound='x.x') }}
    - ${{ pin_compatible("sofa-python3", lower_bound='x.x', upper_bound='x.x') }}
    - ${{ pin_compatible("sofa-stlib", lower_bound='x.x', upper_bound='x.x') }}
    - ${{ pin_compatible("sofa-softrobots", lower_bound='x.x', upper_bound='x.x') }}  
    - python
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}
tests:
  - package_contents:
      include: 
        - SoftRobots.Inverse/component/config.h
      lib: 
        - SoftRobots.Inverse
      files: 
        - ${{ "Library/" if win }}lib/cmake/SoftRobots.Inverse/SoftRobots.InverseConfig.cmake
        - ${{ "Library/" if win }}lib/cmake/SoftRobots.Inverse/SoftRobots.InverseConfigVersion.cmake

about:
  homepage: https://github.com/SofaDefrost/SoftRobots.Inverse
  summary: Sofa plugin containing inverse method for soft robotics.
  license: AGPL-3.0-only
  license_file:
    - LICENSE.AGPLV3.txt
    - LICENSE.AGPLV3.Clause11.txt
  repository: https://github.com/SofaDefrost/SoftRobots.Inverse

extra:
  recipe-maintainers:
    - olivier-roussel
    - hugtalbot