context:
  name: sofa-modelorderreduction
  version: 25.06.99
  build_num: 0
  major: ${{ (version | split('.'))[0] }}
  minor: ${{ (version | split('.'))[1] }}
  major_minor: ${{ major }}.${{ minor }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/SofaDefrost/ModelOrderReduction.git
  branch: master

build:
  number: ${{ build_num }}
  string: nightly_py${{ python | version_to_buildstring }}h${{ hash }}

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - if: not win
      then: 
        - make
    - if: win
      then: 
        - ninja
    - if: linux
      then: 
        - ${{ cdt('mesa-libgl-devel') }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - pybind11
  host:
    - sofa-devel ==${{ version }}
    - sofa-python3 ==${{ version }}
    - eigen
    - libboost-headers
    - cxxopts
    - python
    - pybind11
  run:
    # we manually pin compatibility between sofa libs and plugins to MAJOR.MINOR versions
    - ${{ pin_compatible('sofa-devel', lower_bound='x.x', upper_bound='x.x') }}
    - ${{ pin_compatible('sofa-python3', lower_bound='x.x', upper_bound='x.x') }}
    - python
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - package_contents:
      include: 
        - ModelOrderReduction/config.h
      lib: 
        - ModelOrderReduction
      files: 
        - ${{ "Library/" if win }}lib/cmake/ModelOrderReduction/ModelOrderReductionConfig.cmake
        - ${{ "Library/" if win }}lib/cmake/ModelOrderReduction/ModelOrderReductionConfigVersion.cmake
  - python:
      imports:
        - mor

about:
  homepage: https://www.sofa-framework.org/applications/marketplace/modelorderreduction/
  summary: SOFA plugin to reduce model.
  license: GPL-2.0-or-later
  license_file: LICENSE
  documentation: https://modelorderreduction.readthedocs.io/en/latest/
  repository: https://github.com/SofaDefrost/ModelOrderReduction

extra:
  recipe-maintainers:
    - olivier-roussel
    - hugtalbot
