context:
  name: sofa-glfw
  version: 25.06.00
  build_num: 3
  major: ${{ (version | split('.'))[0] }}
  minor: ${{ (version | split('.'))[1] }}
  major_minor: ${{ major }}.${{ minor }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/sofa-framework/SofaGLFW.git
  branch: v25.06

build:
  number: ${{ build_num }}

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - if: not win
      then: 
        - make
    - if: win
      then: 
        - ninja
    - if: linux
      then: 
        - ${{ cdt('mesa-libgl-devel') }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - pybind11        
  host:
    - sofa-devel ==${{ version }}
    - sofa-python3 ==${{ version }}
    - sofa-gl ==${{ version }}
    - nativefiledialog-extended
    - libboost-headers
    - eigen
    - cxxopts
    - glfw
    - pybind11
    - python
  run:
    # we manually pin compatibility between sofa libs and plugins to MAJOR.MINOR versions
    - ${{ pin_compatible('sofa-devel', lower_bound='x.x', upper_bound='x.x') }}
    - ${{ pin_compatible('sofa-python3', lower_bound='x.x', upper_bound='x.x') }}
    - ${{ pin_compatible('sofa-gl', lower_bound='x.x', upper_bound='x.x') }}
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - package_contents:
      lib: 
        - SofaGLFW
        - SofaImGui

about:
  homepage: https://github.com/sofa-framework/SofaGLFW
  summary: Quick and simple GUI for SOFA, based on GLFW and Dear ImGui (runtime only).
  license: LGPL-3.0-or-later
  license_file: LICENSE
  repository: https://github.com/sofa-framework/SofaGLFW

extra:
  recipe-maintainers:
    - olivier-roussel
    - hugtalbot
