context:
  name: sofa-softrobots
  version: "25.06.00"
  major: ${{ (version | split('.'))[0] }}
  minor: ${{ (version | split('.'))[1] }}
  major_minor: ${{ major }}.${{ minor }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/SofaDefrost/SoftRobots/archive/refs/tags/release-v${{ major }}.${{ minor }}.tar.gz
  sha256: 14ccc8eccf8c4aad3572f3f63d4228bf32c21d7f9f5402e95da6c1e00aa38f5e

  patches:
    # https://github.com/SofaDefrost/SoftRobots/pull/339
    - patches/0001-only-requires-Qt5-if-interactive-control-cmake-optio.patch

build:
  number: 3

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - pybind11
  host:
    - sofa-devel ${{ major_minor }}.*
    - sofa-stlib ${{ major_minor }}.*
    - eigen
    - libboost-headers
    - cxxopts
    - python
    - pybind11
  run:
    - python
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - package_contents:
      include: 
        - SoftRobots/component/initSoftRobots.h
      lib: 
        - SoftRobots
  - script:
      - cmake-package-check SoftRobots
    requirements:
      run:
        - cmake-package-check
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}             
  - python:
      imports:
        - softrobots

about:
  homepage: https://project.inria.fr/softrobot/
  summary: Sofa plugin containing components & method for soft robotics.
  license: LGPL-3.0-or-later
  license_file: LICENSE
  documentation: https://softrobots.readthedocs.io/
  repository: https://github.com/SofaDefrost/SoftRobots

extra:
  recipe-maintainers:
    - olivier-roussel
    - hugtalbot
