context:
  name: sofa-app
  version: 25.06.99
  build_num: 0
  major: ${{ (version | split('.'))[0] }}
  minor: ${{ (version | split('.'))[1] }}
  major_minor: ${{ major }}.${{ minor }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/sofa-framework/sofa.git
  branch: master

build:
  number: ${{ build_num }}
  string: nightly_py${{ python | version_to_buildstring }}h${{ hash }}

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - if: unix
      then: make
    - if: win
      then: ninja
  host:
    - sofa-devel ==${{ version }}
    - sofa-glfw ==${{ version }}
    - eigen
    - libboost-headers
    - cxxopts        
  run:
    # we manually pin compatibility between sofa libs and plugins to MAJOR.MINOR versions
    - ${{ pin_compatible('libsofa', lower_bound='x.x', upper_bound='x.x') }}
    - ${{ pin_compatible('sofa-glfw', lower_bound='x.x', upper_bound='x.x') }}

tests:
  - package_contents:
      bin:
        - runSofa

about:
  homepage: https://github.com/sofa-framework/sofa.git
  summary: Applications and ressources for the SOFA framework
  license: GPL-2.0-or-later
  license_file: applications/projects/LICENSE.GPL.txt
  repository: https://github.com/sofa-framework/sofa.git

extra:
  recipe-maintainers:
    - olivier-roussel
    - hugtalbot
