context:
  name: sofa-beamadapter
  version: 25.06.99
  build_num: 0
  major: ${{ (version | split('.'))[0] }}
  minor: ${{ (version | split('.'))[1] }}
  major_minor: ${{ major }}.${{ minor }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/sofa-framework/BeamAdapter.git
  branch: master

build:
  number: ${{ build_num }}
  string: nightly_h${{ hash }}

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - if: not win
      then: 
        - make
    - if: win
      then: 
        - ninja
    - if: linux
      then: 
        - ${{ cdt('mesa-libgl-devel') }}
  host:
    - sofa-devel ==${{ version }}
    - eigen
    - libboost-headers
  run:
    # we manually pin compatibility between sofa libs and plugins to MAJOR.MINOR versions
    - ${{ pin_compatible('sofa-devel', lower_bound='x.x', upper_bound='x.x') }}
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - package_contents:
      include: 
        - BeamAdapter/config.h
      lib: 
        - BeamAdapter
      files: 
        - ${{ "Library/" if win }}lib/cmake/BeamAdapter/BeamAdapterConfig.cmake
        - ${{ "Library/" if win }}lib/cmake/BeamAdapter/BeamAdapterConfigVersion.cmake

about:
  homepage: https://www.sofa-framework.org/applications/marketplace/beamadapter/
  summary: Plugin implementing Kirchhoff rods to simulate any 1D flexible structure.
  license: LGPL-2.1-or-later
  license_file: LICENSE.md
  documentation: https://sofa-framework.github.io/BeamAdapter/
  repository: https://github.com/sofa-framework/BeamAdapter

extra:
  recipe-maintainers:
    - olivier-roussel
    - hugtalbot
