context:
  name: sofa-cosserat
  version: 25.06.00
  build_num: 2
  major: ${{ (version | split('.'))[0] }}
  minor: ${{ (version | split('.'))[1] }}
  major_minor: ${{ major }}.${{ minor }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/SofaDefrost/Cosserat.git
  branch: v25.06

build:
  number: ${{ build_num }}

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - if: not win
      then: 
        - make
    - if: win
      then: 
        - ninja
    - if: linux
      then: 
        - ${{ cdt('mesa-libgl-devel') }}
  host:
    - sofa-devel ==${{ version }}
    - sofa-stlib ==${{ version }}
    - sofa-softrobots ==${{ version }}
    - eigen
    - libboost-headers
    - cxxopts
    - pybind11
    - python
  run:
    # we manually pin compatibility between sofa libs and plugins to MAJOR.MINOR versions
    - ${{ pin_compatible('sofa-devel', lower_bound='x.x', upper_bound='x.x') }}
    - ${{ pin_compatible('sofa-stlib', lower_bound='x.x', upper_bound='x.x') }}
    - ${{ pin_compatible('sofa-softrobots', lower_bound='x.x', upper_bound='x.x') }}
    - python
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - package_contents:
      include: 
        - Cosserat/config.h
      lib: 
        - Cosserat
      files: 
        - ${{ "Library/" if win }}lib/cmake/Cosserat/CosseratConfig.cmake
        - ${{ "Library/" if win }}lib/cmake/Cosserat/CosseratConfigVersion.cmake
  - python:
      imports:
        - Sofa
        - Cosserat

about:
  homepage: https://www.sofa-framework.org/applications/plugins/cosserat-beam-cable-needle/
  summary: A SOFA plugin to simulate linear structures using Cosserat theory.
  license: LGPL-3.0-or-later
  license_file: LICENSE
  repository: https://github.com/SofaDefrost/plugin.Cosserat/

extra:
  recipe-maintainers:
    - olivier-roussel
    - hugtalbot
