context:
  name: sofa-softrobots
  version: 25.06.99
  build_num: 0
  major: ${{ (version | split('.'))[0] }}
  minor: ${{ (version | split('.'))[1] }}
  major_minor: ${{ major }}.${{ minor }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/SofaDefrost/SoftRobots.git
  branch: master

build:
  number: ${{ build_num }}
  string: nightly_py${{ python | version_to_buildstring }}h${{ hash }}

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - if: not win
      then: 
        - make
    - if: win
      then: 
        - ninja
    - if: linux
      then: 
        - ${{ cdt('mesa-libgl-devel') }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - pybind11
  host:
    - sofa-devel ==${{ version }}
    - sofa-stlib ==${{ version }}
    - eigen
    - libboost-headers
    - cxxopts
    - python
    - pybind11
  run:
    # we manually pin compatibility between sofa libs and plugins to MAJOR.MINOR versions
    - ${{ pin_compatible('sofa-devel', lower_bound='x.x', upper_bound='x.x') }}
    - ${{ pin_compatible('sofa-stlib', lower_bound='x.x', upper_bound='x.x') }}
    - python
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - package_contents:
      include: 
        - SoftRobots/component/initSoftRobots.h
      lib: 
        - SoftRobots
      files: 
        - ${{ "Library/" if win }}lib/cmake/SoftRobots/SoftRobotsConfig.cmake
        - ${{ "Library/" if win }}lib/cmake/SoftRobots/SoftRobotsConfigVersion.cmake
  - python:
      imports:
        - softrobots

about:
  homepage: https://project.inria.fr/softrobot/
  summary: Sofa plugin containing components & method for soft robotics.
  license: LGPL-3.0-or-later
  license_file: LICENSE
  documentation: https://softrobots.readthedocs.io/
  repository: https://github.com/SofaDefrost/SoftRobots

extra:
  recipe-maintainers:
    - olivier-roussel
    - hugtalbot
