context:
  name: sofa-python3
  version: 24.12.00
  build_num: 0
  major: ${{ (version | split('.'))[0] }}
  minor: ${{ (version | split('.'))[1] }}
  major_minor: ${{ major }}.${{ minor }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/sofa-framework/SofaPython3/archive/refs/tags/release-v${{ major_minor }}.tar.gz
  sha256: 611b93b78bde54252849774c99c5d6d63322b407982357aa2356e26127693619

  patches:
    - patches/cmake-qglviewer.patch
    # See comments in sofa conda package recipe at file
    # scripts/hotfix-sofa-run-macos.sh for more details.
    - if: osx
      then:
        - patches/0001-hotfix-for-libpython-linking-on-macOS.patch

build:
  number: ${{ build_num }}

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - if: not win
      then: 
        - make
    - if: win
      then: 
        - ninja
    - if: linux
      then: 
        - ${{ cdt('mesa-libgl-devel') }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
        - pybind11
  host:
    - sofa-devel ${{ major_minor }}
    - sofa-gl ${{ major_minor }}
    - sofa-gui-qt ${{ major_minor }}
    - eigen
    - libboost-headers
    - glew
    - qt-main
    - cxxopts
    - python
    - numpy
    - pybind11
  run:
    # we manually pin compatibility between sofa libs and plugins to MAJOR.MINOR versions
    - ${{ pin_compatible('sofa-devel', lower_bound='x.x', upper_bound='x.x') }}
    - ${{ pin_compatible('sofa-gl', lower_bound='x.x', upper_bound='x.x') }}
    - ${{ pin_compatible('sofa-gui-qt', lower_bound='x.x', upper_bound='x.x') }}
    - ${{ pin_compatible('numpy') }}
    - python
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - package_contents:
      include: 
        - SofaPython3/config.h
      lib: 
        - SofaPython3
      files: 
        - ${{ "Library/" if win }}lib/cmake/SofaPython3/SofaPython3Config.cmake
        - ${{ "Library/" if win }}lib/cmake/SofaPython3/SofaPython3ConfigVersion.cmake
  - python:
      imports:
        - Sofa.Core

about:
  homepage: https://github.com/sofa-framework/SofaPython3
  summary: A python plugin for Sofa offering a pythonic interface and python3 support.
  license: LGPL-2.1-or-later
  license_file: License.md
  documentation: https://sofapython3.readthedocs.io/
  repository: https://github.com/sofa-framework/SofaPython3

extra:
  recipe-maintainers:
    - olivier-roussel
    - hugtalbot
