context:
  name: sofa-stlib
  version: 25.06.99
  build_num: 0
  major: ${{ (version | split('.'))[0] }}
  minor: ${{ (version | split('.'))[1] }}
  major_minor: ${{ major }}.${{ minor }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/SofaDefrost/STLIB.git
  branch: master

build:
  number: ${{ build_num }}
  string: nightly_py${{ python | version_to_buildstring }}h${{ hash }}

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - if: not win
      then: 
        - make
    - if: win
      then: 
        - ninja
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - pybind11
  host:
    - sofa-python3 ==${{ version }}
    - eigen
    - libboost-headers
    - python
    - pybind11
  run:
    # we manually pin compatibility between sofa libs and plugins to MAJOR.MINOR versions
    - ${{ pin_compatible('sofa-python3', lower_bound='x.x', upper_bound='x.x') }}
    - python
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - package_contents:
      include: 
        - STLIB/initPlugin.h
      lib: 
        - STLIB
      files: 
        - ${{ "Library/" if win }}lib/cmake/STLIB/STLIBConfig.cmake
        - ${{ "Library/" if win }}lib/cmake/STLIB/STLIBConfigVersion.cmake
  - python:
      imports:
        - splib3
about:
  homepage: https://github.com/SofaDefrost/STLIB
  summary: Sofa Template Library containing Sofa scenes templates.
  license: LGPL-3.0-or-later
  license_file: LICENSE
  documentation: https://stlib.readthedocs.io/
  repository: https://github.com/SofaDefrost/STLIB

extra:
  recipe-maintainers:
    - olivier-roussel
    - hugtalbot
