context:
  name: sofa-qt
  version: 25.06.99
  build_num: 0
  major: ${{ (version | split('.'))[0] }}
  minor: ${{ (version | split('.'))[1] }}
  major_minor: ${{ major }}.${{ minor }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/olivier-roussel/Sofa.Qt.git
  branch: allow-external-qglviewer

build:
  number: ${{ build_num }}
  string: nightly_h${{ hash }}
  skip:
    - linux and aarch64

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - if: unix
      then: make
    - if: win
      then: ninja
    - if: linux
      then: ${{ cdt('mesa-libgl-devel') }}
  host:
    - sofa-devel ==${{ version }}
    - sofa-gl ==${{ version }}
    - qt-main
    - ffmpeg
    - libqglviewer
    - eigen
    - libboost-headers
    - cxxopts
  run:
    # we manually pin compatibility between sofa libs and plugins to MAJOR.MINOR versions
    - ${{ pin_compatible('libsofa', lower_bound='x.x', upper_bound='x.x') }}
    - ${{ pin_compatible('sofa-gl', lower_bound='x.x', upper_bound='x.x') }}
    - glew
    - if: linux
      then: libglu
    # these are apparently required by qt on windows
    - if: win
      then:
        - libzlib
        - libjpeg-turbo
        - libpng
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - package_contents:
      include:
        - Sofa.Qt/sofa/qt/init.h
      lib:
        - Sofa.Qt*
      files:
        - ${{ "Library/" if win }}lib/cmake/Sofa.Qt/Sofa.QtConfig.cmake
        - ${{ "Library/" if win }}lib/cmake/Sofa.Qt/Sofa.QtConfigVersion.cmake

about:
  homepage: https://github.com/sofa-framework/Sofa.Qt
  summary: Qt-based GUI library for the SOFA framework
  license: GPL-2.0-or-later
  license_file: LICENSE.GPL.txt
  repository: https://github.com/sofa-framework/Sofa.Qt

extra:
  recipe-maintainers:
    - olivier-roussel
    - hugtalbot
