context:
  name: sofa-beamadapter
  version: "25.06.00"
  major: ${{ (version | split('.'))[0] }}
  minor: ${{ (version | split('.'))[1] }}
  major_minor: ${{ (version | split('.'))[:2] | join('.') }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/sofa-framework/BeamAdapter/archive/refs/tags/release-v${{ major}}.${{ minor }}.tar.gz
  sha256: 003b35cabee99e3eed38faa503f4b2ebef39882597a32d5c8ff655ad94b11afe

build:
  number: 3

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
  host:
    - sofa-devel ==${{ version }}
    - eigen
    - libboost-headers
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - package_contents:
      include: 
        - BeamAdapter/config.h
      lib: 
        - BeamAdapter
  - script:
      - cmake-package-check BeamAdapter
    requirements:
      run:
        - cmake-package-check
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}

about:
  homepage: https://www.sofa-framework.org/applications/marketplace/beamadapter/
  summary: Plugin implementing Kirchhoff rods to simulate any 1D flexible structure.
  license: LGPL-2.1-or-later
  license_file: LICENSE.md
  documentation: https://sofa-framework.github.io/BeamAdapter/
  repository: https://github.com/sofa-framework/BeamAdapter

extra:
  recipe-maintainers:
    - olivier-roussel
    - hugtalbot
