context:
  name: sofa-modelorderreduction
  version: "25.06.00"
  major: ${{ (version | split('.'))[0] }}
  minor: ${{ (version | split('.'))[1] }}
  major_minor: ${{ (version | split('.'))[:2] | join('.') }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/SofaDefrost/ModelOrderReduction/archive/refs/tags/release-v${{ major }}.${{ minor }}.tar.gz
  sha256: 214481e12b0038a8b0fddaa18b4b36528b737df2714866d18a843e2a0ad952d4

build:
  number: 3

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - pybind11
  host:
    - sofa-devel ${{ major_minor }}.*
    - sofa-python3 ${{ major_minor }}.*
    - eigen
    - libboost-headers
    - cxxopts
    - python
    - pybind11
  run:
    - python
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - package_contents:
      include: 
        - ModelOrderReduction/config.h
      lib: 
        - ModelOrderReduction
  - script:
      - cmake-package-check ModelOrderReduction
    requirements:
      run:
        - cmake-package-check
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}        
  - python:
      imports:
        - mor

about:
  homepage: https://www.sofa-framework.org/applications/marketplace/modelorderreduction/
  summary: SOFA plugin to reduce model.
  license: GPL-2.0-or-later
  license_file: LICENSE
  documentation: https://modelorderreduction.readthedocs.io/en/latest/
  repository: https://github.com/SofaDefrost/ModelOrderReduction

extra:
  recipe-maintainers:
    - olivier-roussel
    - hugtalbot
