name: debug-label
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types:
    - opened
    - reopened
    - unlabeled
    paths:
      - '**/release-*/sofa-python3/.ci_support/*.yaml'

jobs:
  check-depends-on-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if depends-on
        shell: bash -l {0}
        if: ${{ contains(github.event.pull_request.labels.*.name, 'depends-on') }}
        run: |
          echo "Pull Request was open with a depends-on label and is blocked."
          echo "Merge listed PRs in comment first and unlabel this PR."
          exit 1

      - name: Continue otherwise
        shell: bash -l {0}
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'depends-on') }}
        run: |
          echo "Pull Request was not opened with a depends-on label, continuing..."

  build-publish-sofa:
    runs-on: ubuntu-latest
    needs: check-depends-on-PR
    steps:
      - name: Run CI
        shell: bash -l {0}
        run: |
          echo "Running CI...""