name: Re-render package

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      release:
        required: true
        type: string
      requires-prs:
        required: true
        type: string
    outputs:
      output-pr:
        value: ${{ jobs.rerender.outputs.output-pr-number }}

jobs:
  rerender:
    name: Re-render package ${{ inputs.package }}-${{ inputs.release }} (requires ${{ inputs.requires-prs }} )
    runs-on:  ubuntu-latest
    outputs:
      output-pr-number: ${{ steps.set-outputs.outputs.pull-request-number }}
    steps:
    - uses: actions/checkout@v4

    - name: Install miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        miniforge-version: latest
        channels: conda-forge

    - name: Install tools using conda
      shell: bash -l {0}
      run: conda install conda-smithy python pyyaml git

    - name: Re-render ${{ inputs.release }}/${{ inputs.package }} using conda smithy and filter configs
      shell: bash -l {0}
      run: |
        CONDA_BUILD_CONFIG_FILE=conda/configs/conda-build.yaml
        PACKAGE_DIR=conda/recipes/${{ inputs.release }}/${{ inputs.package }}
        echo "PACKAGE_DIR=$PACKAGE_DIR" >> $GITHUB_ENV
        bash scripts/rerender.sh $CONDA_BUILD_CONFIG_FILE $PACKAGE_DIR

    - name: Check if at least one config needs update
      shell: bash -l {0}
      run: |
        set +e
        git diff --exit-code $PACKAGE_DIR/.ci_support/*.yaml
        NEEDS_UPDATE=$?
        echo "NEEDS_UPDATE=$NEEDS_UPDATE" >> $GITHUB_ENV
        if [[ $NEEDS_UPDATE -eq 0 ]]; then
          echo "Feedstock does not need update"
        else
          echo "Feedstock needs update"
        fi

    - name: Bump recipe build number
      if: ${{ env.NEEDS_UPDATE == 1 }}
      run: |
        # python scripts/bump_build_number.py ${{ env.PACKAGE_DIR }}/recipe/recipe.yaml
        RESULT=$(python scripts/bump_build_number.py ${{ env.PACKAGE_DIR }}/recipe/recipe.yaml)
        NEW_BUILD_NUMBER=$(echo "$RESULT" | jq -r '.new_build_number')
        echo "==== NEW_BUILD_NUMBER = $NEW_BUILD_NUMBER"
        echo "NEW_BUILD_NUMBER=$NEW_BUILD_NUMBER" >> $GITHUB_ENV
        echo "BRANCH_NAME=rerender/${{ inputs.package }}/${{ inputs.release }}/build_$NEW_BUILD_NUMBER" >> $GITHUB_ENV

    - name: Debug - Echo
      run: echo "${{ inputs.requires-prs }}"

    - name: Debug - Dummy Create PR [no requirements]
      # id: create-pr-no-require
      if: ${{ env.NEEDS_UPDATE == 1 && inputs.requires-prs == '' }}
      run: echo "-- Creating PR with no requirements"

    - name: Debug - Dummy Create PR [requires PRs ${{ inputs.requires-prs }} ]
      # id: create-pr-requires
      if: ${{ env.NEEDS_UPDATE == 1 && inputs.requires-prs != '' }}
      run: echo "-- Creating PR that requires PRs ${{ inputs.requires-prs }}"

    - name: Debug - Output required PRs
      # id: set-outputs
      if: ${{ env.NEEDS_UPDATE == 1 }}
      run: echo "output-pr-number=42" >> $GITHUB_OUTPUT

    # - name: Create PR [no requirements]
    #   id: create-pr-no-require
    #   if: ${{ env.NEEDS_UPDATE == 1 && inputs.requires-prs == '' }}
    #   uses: peter-evans/create-pull-request@v7
    #   with:
    #     base: master
    #     token: ${{ secrets.TEST_PAT }}
    #     commit-message: Rebuild ${{ inputs.package }}/${{ inputs.release }} build number ${{ env.NEW_BUILD_NUMBER }}
    #     committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
    #     author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
    #     branch: ${{ env.BRANCH_NAME }}
    #     delete-branch: true
    #     labels: rerender
    #     add-paths: |
    #         ${{ env.PACKAGE_DIR }}/recipe/recipe.yaml
    #         ${{ env.PACKAGE_DIR }}/.ci_support/*.yaml
    #     title: '[Rebuild] Rebuild ${{ inputs.package }}/${{ inputs.release }} build ${{ env.NEW_BUILD_NUMBER }}'
    #     body: |
    #       Rebuild package ${{ inputs.package }}:
    #         - version ${{ inputs.release }}
    #         - new build number: ${{ env.NEW_BUILD_NUMBER }}
    #       --
    #       Auto-generated by [create-pull-request][1]
    #       [1]: https://github.com/peter-evans/create-pull-request

    # - name: Create PR [requires PRs ${{ inputs.requires-prs }} ]
    #   id: create-pr-requires
    #   if: ${{ env.NEEDS_UPDATE == 1 && inputs.requires-prs != '' }}
    #   uses: peter-evans/create-pull-request@v7
    #   with:
    #     base: master
    #     token: ${{ secrets.TEST_PAT }}
    #     commit-message: Rebuild ${{ inputs.package }}/${{ inputs.release }} build number ${{ env.NEW_BUILD_NUMBER }}
    #     committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
    #     author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
    #     branch: ${{ env.BRANCH_NAME }}
    #     delete-branch: true
    #     labels: rerender, depends-on
    #     add-paths: |
    #         ${{ env.PACKAGE_DIR }}/recipe/recipe.yaml
    #         ${{ env.PACKAGE_DIR }}/.ci_support/*.yaml
    #     title: '[Rebuild] Rebuild ${{ inputs.package }}/${{ inputs.release }} build ${{ env.NEW_BUILD_NUMBER }}'
    #     body: |
    #       Rebuild package ${{ inputs.package }}:
    #         - version ${{ inputs.release }}
    #         - new build number: ${{ env.NEW_BUILD_NUMBER }}
    #         - Depends-on PRs: ${{ inputs.requires-prs }}
    #       --
    #       Auto-generated by [create-pull-request][1]
    #       [1]: https://github.com/peter-evans/create-pull-request          

    # - name: Output required PRs
    #   id: set-outputs
    #   if: ${{ env.NEEDS_UPDATE == 1 }}
    #   run: |
    #     if [ -z "${{ inputs.requires-prs }}" ]; then
    #       echo "output-pr-number=${{ steps.create-pr-no-require.outputs.pull-request-number }}" >> $GITHUB_OUTPUT
    #       echo "Set output output-pr-number to ${{ steps.create-pr-no-require.outputs.pull-request-number }} (no requires case)"
    #     else
    #       echo "output-pr-number=${{ steps.create-pr-requires.outputs.pull-request-number }}" >> $GITHUB_OUTPUT
    #       echo "Set output output-pr-number to ${{ steps.create-pr-requires.outputs.pull-request-number }} (requires case)"
    #     fi
    #     echo $GITHUB_OUTPUT