name: sofa-python3
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types:
    - opened
    - reopened
    - unlabeled
    # paths:
    #   - '**/release-*/sofa-python3/.ci_support/*.yaml'

jobs:
  check-depends-on-PR:
    if: contains(github.event.pull_request.labels.*.name, 'depends-on')
    runs-on: ubuntu-latest
    steps:
      - name: Fail in case Pull Request is opened with label "depends-on"
        if: ${{ contains(github.event.pull_request.labels.*.name, 'depends-on') }}
        run: |
          echo "Pull Request was open with a depends-on label and is blocked."
          echo "Merge listed PRs in comment first and unlabel this PR."
          exit 1

      - name: Succeed otherwise
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'depends-on') }}
        run: |
          echo "Pull Request was not opened with a depends-on label, continuing..."

  build-publish-sofa-python3:
    strategy:
      fail-fast: false
      matrix:
        target: [{platform: "linux-64", runner: "ubuntu-latest"},
                  {platform: "linux-aarch64", runner: "ubuntu-22.04-arm"},
                  {platform: "osx-64", runner: "macos-15-intel"},
                  {platform: "osx-arm64", runner: "macos-15"},
                  {platform: "win-64", runner: "windows-latest"}]
        python: ["3.10", "3.11", "3.12", "3.13"]

    uses: ./.github/workflows/build_publish_package.yml
    needs: check-depends-on-PR
    with:
      package-name: sofa-python3
      runner: ${{ matrix.target.runner }}
      platform: ${{ matrix.target.platform }}
      python: ${{ matrix.python }}
      channel: sofa-framework
      recipe-dir: release-v25.06
    secrets:
      api-key: ${{ secrets.PREFIXDEV_APIKEY }}