name: sofa
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types:
    - opened
    - labeled
    - unlabeled
    paths:
      - '**/release-*/sofa/.ci_support/*.yaml'

jobs:
  check-depends-on-PR:
    if: contains(github.event.pull_request.labels.*.name, 'depends-on')
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Fail in case Pull Request is labeled with "depends-on"
        run: |
          echo "Pull Request has a depends-on label and is blocked."
          echo "Merge listed PRs in comment first and unlabel this PR."
          exit 1

  build-publish-sofa:
    strategy:
      fail-fast: false
      matrix:
        target: [{platform: "linux-64", runner: "ubuntu-latest"},
                 {platform: "linux-aarch64", runner: "ubuntu-22.04-arm"},
                 {platform: "osx-64", runner: "macos-15-intel"},
                 {platform: "osx-arm64", runner: "macos-15"},
                 {platform: "win-64", runner: "windows-latest"}]

    uses: ./.github/workflows/build_publish_package.yml
    with:
      package-name: sofa
      runner: ${{ matrix.target.runner }}
      platform: ${{ matrix.target.platform }}
      channel: sofa-framework
      recipe-dir: release-v25.06
    secrets:
      api-key: ${{ secrets.PREFIXDEV_APIKEY }}