name: sofa
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types:
      - opened

jobs:
  build-publish-sofa:
    strategy:
      fail-fast: false
      matrix:
        target: [{platform: "linux-64", runner: "ubuntu-latest"},
                 {platform: "linux-aarch64", runner: "ubuntu-22.04-arm"},
                 {platform: "osx-64", runner: "macos-13"},
                 {platform: "osx-arm64", runner: "macos-14"},
                 {platform: "win-64", runner: "windows-latest"}]

    uses: ./.github/workflows/build_publish_package.yml
    with:
      package-name: sofa
      runner: ${{ matrix.target.runner }}
      platform: ${{ matrix.target.platform }}
      anaconda-channel: sofa-framework
      recipe-dir: release-v25.06
    secrets:
      anaconda-token: ${{ secrets.ANACONDA_TOKEN }}