name: sofa-python3
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/release-v25.06/sofa-python3/.ci_support/*.yaml'

jobs:
  build-publish-sofa-python3:
    strategy:
      fail-fast: false
      matrix:
        target: [{platform: "linux-64", runner: "ubuntu-latest"},
                  {platform: "linux-aarch64", runner: "ubuntu-22.04-arm"},
                  {platform: "osx-64", runner: "macos-15"},
                  {platform: "osx-arm64", runner: "macos-15"},
                  {platform: "win-64", runner: "windows-latest"}]
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    uses: ./.github/workflows/build_publish_package.yml
    with:
      package-name: sofa-python3
      runner: ${{ matrix.target.runner }}
      platform: ${{ matrix.target.platform }}
      python: ${{ matrix.python }}
      channel: sofa-framework
      recipe-dir: release-v25.06
    secrets:
      api-key: ${{ secrets.PREFIXDEV_APIKEY }}